# Étape 1 : build de l'app
FROM node:18-bullseye AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Étape 2 : exécuter l'app en prod
FROM node:18-bullseye AS runner

WORKDIR /app

# Copier uniquement ce qu'il faut pour exécuter l'app
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/tsconfig.json ./tsconfig.json

ENV NODE_ENV=production

EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]
